### ISSUE TITLE
MVP & Project Setup:

### ISSUE THREAD

**Issue by michaelfitzhavey** [holistic-web/portfolio-fabricator#1]
# Initial Concept

### Context
A JSON object describing the developer. It looks like:
```
{
    name: {
        first: string // 'Michael',
        last:  string // 'Fitzhavey'
    },
    profession: string // 'Developer',
    profileImageUrl: string // 'https://i.imgur.com/Pm8kKel.jpg',
    aboutMe: string // 'Full Stack developer based in London. Specialising in Node.js, Firebase & Vue. I use agile development methods and cutting edge web technonology to deliver rapid results.',
    contact: {
        email: string // 'michael@fitzhavey.com',
        telephone: string // '+123456789'
    },
    education: [
        {
             institution: string // 'westminster school',
             date: string // '2012-2015'
             qualifications: [
                 string // 'GCSE maths: A'
             ]
        }
    ],
    experience: [
        {
             date: string // 'March 2015 - Present',
             organisation: string // 'Alphabet inc',
             role: string // 'Full Stack Devops Engineer X Power Ranger',
             description: string // 'I maintained over 50 websites managing...',
             projects: [
                 string // 'I did this thing in javascript for that reason'
             ]
        }  
    ]
    externalProfiles: {
        github: string: // 'michaelfitzhavey',
        linkedIn: string: // 'whatevertheurlis',
        stackOverflow: string: // 'michaelfitzhavey'
   }
}
```

#### Design / Appearance
It will be a single page with a linear structure. If any data is missing that feature should gracefully degrade to a hidden state rather than showing any broken features.

## Todo:
- [x] build basic site with static data
- [x] populate that site from a context object
- [x] store the schema somewhere visible, maybe the readme
- [x] set which parts of the schema are optional and ensure that site works if they are not provided
- [ ] ~~allow the user to set some details of the site, such as the colour scheme from another config~~
- [ ] ~~randomise displayed picture~~
    _These have been moved into the roadmap_

## Wider Scope
_Things that are outside of the MVP scope. These should be documented elsewhere before closing this issue..._
- let dev add custom components to their site
- let dev add content in markdown (maybe as blog posts?)
- allow user inputed text to be rendered as markdown
- add default values for some things in context
- have a 'job hunting dashboard'

**Comment by Charlielancaster** [comment]
steal ideas from http://lukeforsythe.com/

**Comment by michaelfitzhavey** [comment]
# Design for Education & Experience sections
_lol_
![IMG_20190502_233434](https://user-images.githubusercontent.com/2746248/57111204-15528500-6d33-11e9-9def-80dff23b12c8.jpg)

**Comment by Charlielancaster** [comment]
basic iz best!

**Comment by michaelfitzhavey** [comment]
Work on creating the design aspect of these tasks has been started in #2

**Comment by michaelfitzhavey** [comment]
Work creating the admin side of this and allowing users to populate their own context object has started in #3

**Comment by Charlielancaster** [comment]
Work for improving the design of template 1 has been started in #4

**Comment by michaelfitzhavey** [comment]
For the final two bullet points:
- > allow the user to set some details of the site, such as the colour scheme from another config`
    _let's inject a style tag `<style></style>` that adds some classes such as `.theme-colour`, `.alt-colour`, etc_
- > randomise displayed picture
    _ let's have the displayed picture be a customisable value in a new part of the context object for now, maybe layout? or maybe make context no longer top level and have it as the first property of a new `layout` object?_

**Comment by michaelfitzhavey** [comment]
#3 has been closed as we decided it didn't make sense to tightly couple the admin interface and the displayed website. #4 has been updated to create an mvp front end web app

**Comment by michaelfitzhavey** [comment]
I've documented the roadmap in #4 and it is now ready to merge, once merged that should resolve this issue 😄
